package com.yaser.service.product_type_service;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b14002 Generated source version: 2.2
 * 
 */
@WebFault(name = "DatatypeConfigurationException", targetNamespace = "http://intf.service.regularpayment.api.cca.hmn.ykb.com/")
public class DatatypeConfigurationException_Exception extends Exception {
    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DatatypeConfigurationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public DatatypeConfigurationException_Exception(String message, DatatypeConfigurationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public DatatypeConfigurationException_Exception(String message, DatatypeConfigurationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return returns fault bean: com.yaser.service.DatatypeConfigurationException
     */
    public DatatypeConfigurationException getFaultInfo() {
        return faultInfo;
    }
}
