package com.yaser.service.product_type_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b14002 Generated source version: 2.2
 * 
 */
@WebService(name = "ICcaApiRegularPaymentProductsService", targetNamespace = "http://intf.service.regularpayment.api.cca.hmn.ykb.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface ICcaApiRegularPaymentProductsService {
    /**
     * 
     * @param request
     * @return returns com.yaser.service.ResponseApiRegularPaymentProducts
     * @throws DatatypeConfigurationException_Exception
     * @throws HmnServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRegularPaymentProducts", targetNamespace = "http://intf.service.regularpayment.api.cca.hmn.ykb.com/", className = "com.yaser.service.product_type_service.GetRegularPaymentProducts")
    @ResponseWrapper(localName = "getRegularPaymentProductsResponse", targetNamespace = "http://intf.service.regularpayment.api.cca.hmn.ykb.com/", className = "com.yaser.service.product_type_service.GetRegularPaymentProductsResponse")
    public ResponseApiRegularPaymentProducts getRegularPaymentProducts(@WebParam(name = "arg0", targetNamespace = "") RequestApiRegularPaymentProducts request)
            throws DatatypeConfigurationException_Exception, HmnServiceException_Exception;
}
