
package com.yaser.service.regular_payment_insert;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "HmnServiceException", targetNamespace = "http://intf.service.web.api.cca.hmn.ykb.com/")
public class HmnServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private HmnServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HmnServiceException_Exception(String message, HmnServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HmnServiceException_Exception(String message, HmnServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.yaser.service.regular_payment_insert.HmnServiceException
     */
    public HmnServiceException getFaultInfo() {
        return faultInfo;
    }

}
