
package com.yaser.service.regular_payment_insert;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICcaApiWebRegularPaymentInsertService", targetNamespace = "http://intf.service.web.api.cca.hmn.ykb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICcaApiWebRegularPaymentInsertService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.yaser.service.regular_payment_insert.ResponseApiWebRegularPaymentApplicationInsert
     * @throws DatatypeConfigurationException_Exception
     * @throws HmnServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nwbRegularPaymentInsert", targetNamespace = "http://intf.service.web.api.cca.hmn.ykb.com/", className = "com.yaser.service.regular_payment_insert.NwbRegularPaymentInsert")
    @ResponseWrapper(localName = "nwbRegularPaymentInsertResponse", targetNamespace = "http://intf.service.web.api.cca.hmn.ykb.com/", className = "com.yaser.service.regular_payment_insert.NwbRegularPaymentInsertResponse")
    public ResponseApiWebRegularPaymentApplicationInsert nwbRegularPaymentInsert(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestApiWebRegularPaymentApplicationInsert arg0)
        throws DatatypeConfigurationException_Exception, HmnServiceException_Exception
    ;

}
