<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.web.api.cca.hmn.ykb.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://intf.service.web.api.cca.hmn.ykb.com/" name="CcaApiWebRegularPaymentInsertServiceService" targetNamespace="http://service.web.api.cca.hmn.ykb.com/">
  <wsdl:import location="http://betest.yapikredi.com.tr:9083/Harmoni/Cca/Api/Web/CcaApiWebRegularPaymentInsertService?wsdl=ICcaApiWebRegularPaymentInsertService.wsdl" namespace="http://intf.service.web.api.cca.hmn.ykb.com/">
    </wsdl:import>
  <wsdl:binding name="CcaApiWebRegularPaymentInsertServiceServiceSoapBinding" type="ns1:ICcaApiWebRegularPaymentInsertService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="nwbRegularPaymentInsert">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="nwbRegularPaymentInsert">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="nwbRegularPaymentInsertResponse">
        <soap:body use="literal"/>
      </wsdl:output>
      <wsdl:fault name="DatatypeConfigurationException">
        <soap:fault name="DatatypeConfigurationException" use="literal"/>
      </wsdl:fault>
      <wsdl:fault name="HmnServiceException">
        <soap:fault name="HmnServiceException" use="literal"/>
      </wsdl:fault>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="CcaApiWebRegularPaymentInsertServiceService">
    <wsdl:port binding="tns:CcaApiWebRegularPaymentInsertServiceServiceSoapBinding" name="CcaApiWebRegularPaymentInsertServicePort">
      <soap:address location="http://betest.yapikredi.com.tr:9083/Harmoni/Cca/Api/Web/CcaApiWebRegularPaymentInsertService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>