
package com.yaser.service.limit_inquiry_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CcaApiPaymentSystemConsumerLimitServiceService", targetNamespace = "http://service.paymentsystem.api.cca.hmn.ykb.com/", wsdlLocation = "file:/D:/dev/projects/github/GuvenleKirala/KiramGuvendeRemote/src/main/resources/wsdl/ConsumerLimitService.wsdl")
public class CcaApiPaymentSystemConsumerLimitServiceService
    extends Service
{

    private final static URL CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_EXCEPTION;
    private final static QName CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_QNAME = new QName("http://service.paymentsystem.api.cca.hmn.ykb.com/", "CcaApiPaymentSystemConsumerLimitServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/dev/projects/github/GuvenleKirala/KiramGuvendeRemote/src/main/resources/wsdl/ConsumerLimitService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_WSDL_LOCATION = url;
        CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_EXCEPTION = e;
    }

    public CcaApiPaymentSystemConsumerLimitServiceService() {
        super(__getWsdlLocation(), CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_QNAME);
    }

    public CcaApiPaymentSystemConsumerLimitServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_QNAME, features);
    }

    public CcaApiPaymentSystemConsumerLimitServiceService(URL wsdlLocation) {
        super(wsdlLocation, CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_QNAME);
    }

    public CcaApiPaymentSystemConsumerLimitServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_QNAME, features);
    }

    public CcaApiPaymentSystemConsumerLimitServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CcaApiPaymentSystemConsumerLimitServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICcaApiPaymentSystemConsumerLimitService
     */
    @WebEndpoint(name = "CcaApiPaymentSystemConsumerLimitServicePort")
    public ICcaApiPaymentSystemConsumerLimitService getCcaApiPaymentSystemConsumerLimitServicePort() {
        return super.getPort(new QName("http://service.paymentsystem.api.cca.hmn.ykb.com/", "CcaApiPaymentSystemConsumerLimitServicePort"), ICcaApiPaymentSystemConsumerLimitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICcaApiPaymentSystemConsumerLimitService
     */
    @WebEndpoint(name = "CcaApiPaymentSystemConsumerLimitServicePort")
    public ICcaApiPaymentSystemConsumerLimitService getCcaApiPaymentSystemConsumerLimitServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.paymentsystem.api.cca.hmn.ykb.com/", "CcaApiPaymentSystemConsumerLimitServicePort"), ICcaApiPaymentSystemConsumerLimitService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_EXCEPTION!= null) {
            throw CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_EXCEPTION;
        }
        return CCAAPIPAYMENTSYSTEMCONSUMERLIMITSERVICESERVICE_WSDL_LOCATION;
    }

}
