
package com.yaser.service.limit_inquiry_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICcaApiPaymentSystemConsumerLimitService", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ICcaApiPaymentSystemConsumerLimitService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.yaser.service.limit_inquiry_service.ResponseApiPaymentSystemConsumerLimitInquiry
     * @throws HmnServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consumerLimitInquiry", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.ConsumerLimitInquiry")
    @ResponseWrapper(localName = "consumerLimitInquiryResponse", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.ConsumerLimitInquiryResponse")
    public ResponseApiPaymentSystemConsumerLimitInquiry consumerLimitInquiry(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestApiPaymentSystemConsumerLimitInquiry arg0)
        throws HmnServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.yaser.service.limit_inquiry_service.ResponseApiPaymentSystemDisburseOverDraftLimit
     * @throws HmnServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "disburseOverDraftLimit", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.DisburseOverDraftLimit")
    @ResponseWrapper(localName = "disburseOverDraftLimitResponse", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.DisburseOverDraftLimitResponse")
    public ResponseApiPaymentSystemDisburseOverDraftLimit disburseOverDraftLimit(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestApiPaymentSystemDisburseOverDraftLimit arg0)
        throws HmnServiceException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.yaser.service.limit_inquiry_service.ResponseApiPaymentSystemGetOverDraftList
     * @throws HmnServiceException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOverDraftList", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.GetOverDraftList")
    @ResponseWrapper(localName = "getOverDraftListResponse", targetNamespace = "http://intf.service.paymentsystem.api.cca.hmn.ykb.com/", className = "com.yaser.service.limit_inquiry_service.GetOverDraftListResponse")
    public ResponseApiPaymentSystemGetOverDraftList getOverDraftList(
        @WebParam(name = "arg0", targetNamespace = "")
        RequestApiPaymentSystemGetOverDraftList arg0)
        throws HmnServiceException_Exception
    ;

}
